name: Automatic Updates

on:
  schedule:
    - cron: "30 3 * * 5"
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    name: Automatic Updates

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.repo_token }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
          node-version: 18.x

      - name: Check and apply dependencies updates
        run: |
          # Check for updates, and exit script on error / no updates found
          npx '@juit/check-updates' \
            package.json workspaces/*/package.json \
            || exit $(( $? == 255 ? 0 : $? ))

          # If still here, bump the version and reinstall dependencies
          npm version patch --no-git-tag
          rm -rf node-modules package-lock.json
          npm install --workspaces

          # Build our package
          npm run build

          # Re-generate exports from the "dist" directory and align versions
          npm run build exports

          # Commit all changes and push them back to the repo
          git config user.email 'developers@juit.com'
          git config user.name 'Github Workflows'
          git commit -a -m "Release for automatic updates $(date '+%Y-%m-%d %H:%M:%S')"
          git push -u origin '${{ github.ref_name }}'
